"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "#ffffff" # koda.highlight (clean blue)

[character]
success_symbol = "[\\$](#ffffff)"
error_symbol = "[\\$](#ff7676)"

[git_branch]
format = "[$branch]($style)"
style = "#474747" # koda.dim

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](#f2a4db) ($ahead_behind$stashed)]($style)" # Using koda.pink for the text block inside
style = "#701516"
conflicted = ""
untracked = ""
modified = ""
staged = ""
renamed = ""
deleted = ""
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#474747" # koda.dim

[cmd_duration]
format = "[$duration]($style) "
style = "#d9ba73" # koda.warning / const (warm yellow)

[python]
format = "[$virtualenv]($style) "
style = "#50585d" # koda.comment (gives your virtualenv a distinct gray from dim)
detect_extensions = []
detect_files = []
