"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "#ffffff"

[character]
success_symbol = "[\\$](#ffffff)"
error_symbol = "[\\$](#ff7676)"

[git_branch]
format = "[$branch]($style)"
style = "#474747"

[git_status]
format = "([*$all_status$ahead_behind$stashed]($style) )"
style = "#474747"

conflicted = "\u200B"
untracked = "\u200B"
modified = "\u200B"
staged = "\u200B"
renamed = "\u200B"
deleted = "\u200B"
typechanged = "\u200B"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#474747"

[cmd_duration]
format = "[$duration]($style) "
style = "#d9ba73"

[python]
format = "[$virtualenv]($style) "
style = "#50585d"
detect_extensions = []
detect_files = []
